root:
  users: ['admin']
  children:
    - __kemal__:
        users: ['*']
    - css:
        users: ['*']
    - js:
        users: ['*']
    - engineering:
        users: ['john']
    - management:
        users: ['brown']
        children:
          - executive:
              users: ['george', 'wilma', 'mary']
          - marketing:
              users: ['mary']
              children:
                - ads:
                    users: ['george']
